-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Paź 29, 2023 at 06:35 PM
-- Wersja serwera: 10.4.28-MariaDB
-- Wersja PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `holika-holika`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `cosmetics`
--

CREATE TABLE `cosmetics` (
  `ID` int(11) NOT NULL,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `id_type1` int(11) DEFAULT NULL,
  `id_type2` int(11) DEFAULT NULL,
  `id_type3` int(11) DEFAULT NULL,
  `img` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `date` date NOT NULL,
  `shortDescription` text NOT NULL,
  `description` text NOT NULL,
  `ingredients` text NOT NULL,
  `quantity` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `cosmetics`
--

INSERT INTO `cosmetics` (`ID`, `name`, `id_type1`, `id_type2`, `id_type3`, `img`, `price`, `date`, `shortDescription`, `description`, `ingredients`, `quantity`) VALUES
(1, 'Krem z ceramidami', 1, NULL, NULL, 'images/products/good-cera-krem.png', 119.00, '2020-09-20', 'Good cera Krem nawilżający z ceramidami 60ml', 'Stworzony specjalnie z myślą o intensywnym nawilżeniu i odżywieniu podczas zimnych pór roku. To właśnie krem nawilżający z ceramidami Holika Holika Good Cera, który skutecznie nawilża i odżywia suchą, wrażliwą i podrażnioną skórę. Przywróci Twojej skórze również elastyczność i delikatność, zabezpieczając ją barierą ochronną. Dzięki ceramidom w składzie eliminuje również podrażnienia i zaczerwienienia, które często występują w zimnych miesiącach roku. Z Holika Holika Good Cera będziesz i Ty móc cieszyć się zdrową i chronioną cerą.', 'WATER, BUTYLENE GLYCOL, GLYCERIN, CYCLOPENTASILOXANE, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, ETHYLHEXYL ISONONANOATE, HYDROGENATED POLYISOBUTENE, GLYCERYL STEARATE, 1,2-HEXANEDIOL, CETEARYL ALCOHOL, STEARIC ACID, POLYSORBATE 60, POLYGLYCERYL-3 METHYLGLUCOSE DISTEARATE, PENTAERYTHRITYL TETRAETHYLHEXANOATE, STEARYL BEHENATE, DIMETHICONE, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, CETEARYL GLUCOSIDE, PHYTOSTERYL/ISOSTEARYL/CETYL/STEARYL/BEHENYL DIMER DILINOLEATE, CERAMIDE NP, HYDROGENATED POLYDECENE, BUTYROSPERMUM PARKII (SHEA) BUTTER, CETEARETH-20, GLYCERYL CITRATE/LACTATE/LINOLEATE/OLEATE, HYDROXYPROPYL BISPALMITAMIDE MEA, GLYCOSPHINGOLIPIDS, CERAMIDE AP, MEADOWFOAM ESTOLIDE, GLYCINE SOJA (SOYBEAN) STEROLS, CAPRYLIC/CAPRIC TRIGLYCERIDE, CERAMIDE EOP, GLYCERYL POLYMETHACRYLATE, ALEURITIC ACID, YEAST EXTRACT, GLYCOPROTEINS, BETAINE, SODIUM HYALURONATE, POLYQUATERNIUM-51, COCOS NUCIFERA OIL(COCONUT OIL), ALOE BARBADENSIS LEAF EXTRACT, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SQUALANE, CARBOMER, TROMETHAMINE, TOCOPHERYL ACETATE, GLYCERYLAMIDOETHYL METHACRYLATE/STEARYL METHACRYLATE COPOLYMER, ALTEROMONAS FERMENT EXTRACT, BACILLUS FERMENT, PROPYLENE GLYCOL, THEOBROMA CACAO (COCOA) SEED EXTRACT, DIPROPYLENE GLYCOL, LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL, CITRUS GRANDIS (GRAPEFRUIT) PEEL OIL, CYMBOPOGON CITRATUS LEAF OIL, PELARGONIUM GRAVEOLENS OIL, CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL, POGOSTEMON CABLIN OIL, SANTALUM ALBUM (SANDALWOOD) OIL, CHAMOMILLA RECUTITA (MATRICARIA) FLOWER OIL, NIACINAMIDE, ALLANTOIN, DISODIUM EDTA, ETHYLHEXYLGLYCERIN', 38),
(2, 'Emulsja z ceramidami', 1, NULL, NULL, 'images/products/good-cera-emulsja.png', 92.00, '2021-05-14', 'Good Cera emulsja nawilżająco-kojąca z ceramidami 130ml', 'Zapewnij swojej skórze normalizację równowagi wodno-tłuszczowej, która utrzymuje Twoją skórę w zdrowym stanie. Emulsja nawilżająco-kojąca z ceramidami Holika Holika Good Cera przywraca skórze jej ochronną warstwę, uelastycznia ją i łagodzi. Skóra jest miękka, głęboko odżywiona, dzięki czemu możesz cieszyć się również z uczucia komfortu.', 'WATER, CYCLOPENTASILOXANE, HYDROGENATED POLYISOBUTENE, BETAINE, GLYCERIN, BUTYLENE GLYCOL, NEOPENTYL GLYCOL DICAPRATE, 1,2-HEXANEDIOL, C14-22 ALCOHOLS, CETEARYL ALCOHOL, DIMETHICONE, HYDROGENATED LECITHIN, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, BATYL ALCOHOL, C12-20 ALKYL GLUCOSIDE, STEARIC ACID, CAPRYLIC/CAPRIC TRIGLYCERIDE, CAMELLIA OLEIFERA SEED OIL, LECITHIN, XANTHAN GUM, DIPROPYLENE GLYCOL, SODIUM HYALURONATE, NIACINAMIDE, LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL, PROPYLENE GLYCOL, CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL, CITRUS GRANDIS (GRAPEFRUIT) PEEL OIL, CYMBOPOGON CITRATUS LEAF OIL, PELARGONIUM GRAVEOLENS OIL, CERAMIDE NP, THEOBROMA CACAO (COCOA) SEED EXTRACT, SANTALUM ALBUM (SANDALWOOD) OIL, ALTEROMONAS FERMENT EXTRACT, GLYCERYLAMIDOETHYL METHACRYLATE/STEARYL METHACRYLATE COPOLYMER, POLYQUATERNIUM-51, CHAMOMILLA RECUTITA (MATRICARIA) FLOWER OIL, POGOSTEMON CABLIN OIL, BACILLUS FERMENT, CERAMIDE AP, CERAMIDE EOP, ALEURITIC ACID, GLYCERYL POLYMETHACRYLATE, GLYCOPROTEINS, YEAST EXTRACT, GLYCERYL STEARATE, PHYTOSTERYL/ISOSTEARYL/CETYL/STEARYL/BEHENYL DIMER DILINOLEATE, ETHYLHEXYL ISONONANOATE, HYDROXYPROPYL BISPALMITAMIDE MEA, GLYCOSPHINGOLIPIDS, MEADOWFOAM ESTOLIDE, GLYCINE SOJA (SOYBEAN) STEROLS, CETEARYL GLUCOSIDE, HYDROGENATED POLYDECENE, ETHYLHEXYLGLYCERIN, TOCOPHERYL ACETATE', 21),
(3, 'Balsam z ceramidami', 1, NULL, NULL, 'images/products/good-cera-balsam.png', 99.00, '2018-01-28', 'Good Cera balsam nawilżający z ceramidami 40ml', 'Czy masz problematyczne obszary na skórze, które pilnie potrzebują ratunku przed wpływem warunków atmosferycznych? Bez względu na to, czy Twoje usta są popękane, masz suche łokcie lub pięty, balsam Holika Holika Good Cera przyniesie Ci ulgę. Skutecznie odżywia, przywraca skórze równowagę i neutralizuje nieprzyjemne uczucie podrażnienia. Jego uniwersalny skład dodatkowo został zaprojektowany dla wszystkich rodzaj skóry. ', 'GLYCERIN, WATER, CETEARYL ALCOHOL, OLEA EUROPAEA (OLIVE) FRUIT OIL, 1,2-HEXANEDIOL, MACADAMIA INTEGRIFOLIA SEED OIL, CETEARYL GLUCOSIDE, GLYCERYL STEARATE, STEARIC ACID, PHYTOSTERYL/ISOSTEARYL/CETYL/STEARYL/BEHENYL DIMER DILINOLEATE, CERAMIDE NP, HYDROGENATED POLYDECENE, BUTYROSPERMUM PARKII (SHEA) BUTTER, CETEARETH-20, GLYCERYL CITRATE/LACTATE/LINOLEATE/OLEATE, BUTYLENE GLYCOL, HYDROXYPROPYL BISPALMITAMIDE MEA, GLYCOSPHINGOLIPIDS, CERAMIDE AP, MEADOWFOAM ESTOLIDE, GLYCINE SOJA (SOYBEAN) STEROLS, ETHYLHEXYL ISONONANOATE, HYDROGENATED LECITHIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, CERAMIDE EOP, ALTEROMONAS FERMENT EXTRACT, BACILLUS FERMENT, GLYCERYLAMIDOETHYL METHACRYLATE/STEARYL METHACRYLATE COPOLYMER, DIPROPYLENE GLYCOL, LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL, CITRUS GRANDIS (GRAPEFRUIT) PEEL OIL, CYMBOPOGON CITRATUS LEAF OIL, PELARGONIUM GRAVEOLENS OIL, CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL, POGOSTEMON CABLIN OIL, SANTALUM ALBUM (SANDALWOOD) OIL, CHAMOMILLA RECUTITA (MATRICARIA) FLOWER OIL, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SQUALANE, POLYSORBATE 60, ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER, TROMETHAMINE, ALLANTOIN, DISODIUM EDTA, PROPYLENE GLYCOL, ETHYLHEXYLGLYCERIN', 68),
(4, 'Krem do twarzy i ciała z ceramidami', 1, NULL, NULL, 'images/products/good-cera-krem-cialo.png', 119.00, '2022-05-25', 'Good Cera krem nawilżający do twarzy i ciała z ceramidami 200ml', 'Świetnie się sprawdzi dla skóry wrażliwej lub podrażnionej, dzięki swej hipoalergicznej formule. To krem Holika Holika Good Cera powstałby eliminować łuszczenie się skóry, podrażnienia i uczucie ściągnięcia skóry. Formuła zawiera ceramidy, które pomagają przywrócić skórze właściwości ochronne i eliminować wpływy środowiska zewnętrznego w zależności od pory roku. Również wygładza drobne zmarszczki, dzięki czemu skóra staje się wygładzona, miękka i jedwabiście gładka.', 'WATER, GLYCERIN, CAPRYLIC/CAPRIC TRIGLYCERIDE, BUTYROSPERMUM PARKII (SHEA) BUTTER, HYDROGENATED POLY (C6-14 OLEFIN), 1,2-HEXANEDIOL, HYDROGENATED POLYDECENE, HYDROXYETHYL ACRYLATE/SODIUM ACRYLOYLDIMETHYL TAURATE COPOLYMER, SQUALANE, BETAINE, DIMETHICONE, METHYLPROPANEDIOL, POLYSORBATE 60, BUTYLENE GLYCOL, ALGAE EXTRACT, ECLIPTA PROSTRATA LEAF EXTRACT, BETA VULGARIS (BEET) ROOT EXTRACT, ROSA HYBRID FLOWER EXTRACT, AVENA SATIVA (OAT) KERNEL EXTRACT, CYNARA SCOLYMUS (ARTICHOKE) LEAF EXTRACT, PTERIS MULTIFIDA EXTRACT, AMARANTHUS CAUDATUS SEED EXTRACT, ULMUS DAVIDIANA ROOT EXTRACT, DIPROPYLENE GLYCOL, HYDROXYPROPYL STARCH PHOSPHATE, BETA-GLUCAN, POLYQUATERNIUM-51, HYDROGENATED LECITHIN, BACILLUS FERMENT, FRUCTOOLIGOSACCHARIDES, HYDROLYZED CORN STARCH, LECITHIN, LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL, CETEARYL ALCOHOL, CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL, CITRUS GRANDIS (GRAPEFRUIT) PEEL OIL, CYMBOPOGON CITRATUS LEAF OIL, GLYCERYL STEARATE, HYDROLYZED HYALURONIC ACID, PELARGONIUM GRAVEOLENS OIL, STEARIC ACID, ALTEROMONAS FERMENT FILTRATE, ETHYLHEXYL ISONONANOATE, PANTHENOL, POGOSTEMON CABLIN OIL, SANTALUM ALBUM (SANDALWOOD) OIL, PHYTOSTERYL/ISOSTEARYL/CETYL/STEARYL/BEHENYL DIMER DILINOLEATE, ANTHEMIS NOBILIS FLOWER OIL, GLYCINE SOJA (SOYBEAN) STEROLS, HYDROXYPROPYL BISPALMITAMIDE MEA, RAFFINOSE, MEADOWFOAM ESTOLIDE, CETEARYL GLUCOSIDE, FOLIC ACID, CHOLESTEROL, GLYCOSPHINGOLIPIDS, CETEARETH-20, GLYCERYL CITRATE/LACTATE/LINOLEATE/OLEATE, TROMETH-AMINE, CERAMIDE AP, CERAMIDE EOP, PALMITOYL PENTAPEPTIDE-4, CERAMIDE NP', 52),
(5, 'Krem do rąk Berry Berry', 10, 9, NULL, 'images/products/au-krem-berry-berry.png', 29.90, '2022-12-17', 'Krem do rąk Berry Berry - Among Us 30ml', 'Krem do rąk marki Holika Holika o działaniu nawilżającym i odżywczym. Doskonale pielęgnuje skórę dłoni. Jego formuła zawiera między innymi jagody acai, jeżyny, żurawinę. Szybko się wchłania i nie pozostawia tłustego filmu na skórze.', 'agua purificada, glicerina, triglicérido caprílico / cáprico, hexanoato de cetiletilo, 1,2-hexanodiol, diestearato de poligliceril-3, aceite de semilla de macadamia, butilenglicol, alcohol se Tearyl, dimeticona, trehalosa, * extracto de hoja de albahaca, * extracto de mandarina , * extracto de limón, * extracto de naranja, estearato de glicerilo, tetraisoestearato de pentaeritritilo, olivaato de cetearilo, polideceno hidrogenado, poliacriloil dimetil taurato de sodio, olivaato de sorbitán, aceite vegetal, alantoína, arginina, carbómero, citrato de estearato de glicerilo, acetato de tocoferilo, acetato de glicerilo, acetato de etilhexido 10, EDTA disódico, fragancia', 12),
(6, 'Krem do rąk Basil Citrus', 10, 9, NULL, 'images/products/au-krem-basil-citrus.png', 29.90, '2022-12-17', 'Krem do rąk Basil Citrus - Among Us 30ml', 'Krem do rąk marki Holika Holika o działaniu nawilżającym i odżywczym. Doskonale pielęgnuje skórę dłoni. Jego formuła zawiera między innymi wyciąg z owoców cytrusowych, ekstrakt z bazylii. Szybko się wchłania i nie pozostawia tłustego filmu na skórze.', 'agua purificada, glicerina, triglicérido caprílico / cáprico, hexanoato de cetiletilo, 1,2-hexanodiol, diestearato de poligliceril-3, aceite de semilla de macadamia, butilenglicol, alcohol se Tearyl, dimeticona, trehalosa, * extracto de hoja de albahaca, * extracto de mandarina , * extracto de limón, * extracto de naranja, estearato de glicerilo, tetraisoestearato de pentaeritritilo, olivaato de cetearilo, polideceno hidrogenado, poliacriloil dimetil taurato de sodio, olivaato de sorbitán, aceite vegetal, alantoína, arginina, carbómero, citrato de estearato de glicerilo, acetato de tocoferilo, acetato de glicerilo, acetato de etilhexido 10, EDTA disódico, fragancia', 3),
(7, 'Krem do rąk Tropical', 10, 9, NULL, 'images/products/au-krem-tropical.png', 29.90, '2022-12-17', 'Krem do rąk Tropical - Among Us 30ml', 'Krem do rąk marki Holika Holika o działaniu nawilżającym i odżywczym. Doskonale pielęgnuje skórę dłoni. Jego formuła zawiera między innymi ekstrakt z ananasa, papai, liczi. Szybko się wchłania i nie pozostawia tłustego filmu na skórze.', 'agua purificada, glicerina, triglicérido caprílico / cáprico, hexanoato de cetiletilo, 1,2-hexanodiol, diestearato de poligliceril-3, aceite de semilla de macadamia, butilenglicol, alcohol se Tearyl, dimeticona, trehalosa, * extracto de hoja de albahaca, * extracto de mandarina , * extracto de limón, * extracto de naranja, estearato de glicerilo, tetraisoestearato de pentaeritritilo, olivaato de cetearilo, polideceno hidrogenado, poliacriloil dimetil taurato de sodio, olivaato de sorbitán, aceite vegetal, alantoína, arginina, carbómero, citrato de estearato de glicerilo, acetato de tocoferilo, acetato de glicerilo, acetato de etilhexido 10, EDTA disódico, fragancia', 6),
(8, 'Daily Fresh Pianka Olive', 10, 2, 4, 'images/products/au-pianka-olive.png', 39.90, '2022-12-17', 'Daily Fresh Pianka Olive- Among Us 150ml', 'Głównym składnikiem tej piany oczyszczającej jest ekstrakt z drożdży fermentowanych. Z kolei świetnie nawilża, wzmacniając ochronę skóry przed wszelkiego rodzaju zagrożeniami zewnętrznymi. Co więcej, ten podstawowy składnik jest zobowiązany do głębokiego odżywienia naskórka, szczególnie w połączeniu z oliwą z oliwek. W ten sposób ta świeża pianka bez wysiłku wnika w powierzchowne warstwy skóry, wzmacniając i oczyszczając przekrwione obszary. Wreszcie proces fermentacji zwiększa poziom przeciwutleniaczy w składnikach, oferując liczne korzyści dla skóry. Wśród nich jest wzrost produkcji kolagenu, a także elastyczność, mniej wyprysków trądzikowych lub poprawa tekstury.', 'Purified water, glycerin, palmitic acid, lauryc acid, stearic acid, potassium hydroxide, myristic acid, cocamidopropyl betaine, glyceryl stearate, piji-100 stearate, pi-8, polyquantium-7, polysolvate 20, hydroxyethylcellulose, sodium, hydroxyethylcellulose', 27),
(9, 'Daily Fresh Pianka Green Tea', 10, 2, 4, 'images/products/au-pianka-green-tea.png', 39.90, '2022-12-17', 'Daily Fresh Pianka Green Tea- Among Us 150ml', 'Głównym składnikiem tej piany oczyszczającej jest ekstrakt ze sfermentowanej zielonej herbaty. W szczególności ma to silne działanie przeciwzapalne, minimalizując obrzęki i odblokowując pory. Jednocześnie łagodzi suchą skórę skłonną do zaczerwienień i wspomaga zdrowszą aktywność komórek. Dzięki temu jest w stanie niwelować oznaki zmęczenia, spowalniać naturalny proces starzenia, a także maksymalizować barierę ochronną skóry. W tym samym stopniu pianka stabilizuje ukrwienie, głęboko odżywiając i nawilżając olejek do cery mieszanej. Co więcej, ten niezbędny środek pielęgnacyjny poprawia strukturę skóry, wzmacniając ją, dzięki czemu jest mniej wrażliwa w kontakcie z zewnętrznymi zagrożeniami.', 'Purified water, glycerin, palmitic acid, lauryc acid, stearic acid, potassium hydroxide, myristic acid, cocamidopropyl betaine, glyceryl stearate, piji-100 stearate, pi-8, polyquantium-7, polysolbate 20, hydroxyethylcellulose, green tea extract', 10),
(10, 'Daily Fresh Pianka Rice', 10, 2, 4, 'images/products/au-pianka-rice.png', 39.90, '2022-12-17', 'Daily Fresh Pianka Rice - Among Us 150ml', 'Głównym składnikiem tej piany oczyszczającej jest ekstrakt z ryżu. W szczególności bogate w aminokwasy, a także minerały, ich rdzeń wzmacnia barierę obronną przed wszelkiego rodzaju zagrożeniami zewnętrznymi. Ponadto ta opcja wygładza zmarszczki/drobne linie i przyspiesza procesy metaboliczne, nawilżając cerę kierowcy. W ten sposób naskórek z pewnością będzie wyglądał jak pierza, ponieważ ta pianka przyczynia się do spowolnienia początkowych oznak starzenia, oferując odświeżające, zmiękczające wykończenie. Dodatkowo regeneruje starzejącą się skórę, ponieważ jej właściwości odżywcze odnawiają komórki i hamują rozwój głębszych zmarszczek. Wreszcie, jest to świetna opcja dla skóry podrażnionej lub skłonnej do trądziku, równoważąca jej koloryt i teksturę.', 'purified water, glycerin, palmitic acid, lauryc acid, stearic acid, potassium hydroxide, myristic acid, cocamidopropyl betaine, glyceryl stearate, piji-100 stearate, pi-8, polyquarterium-7, polysolvate 20, hydroxyethylcellulide, sodium, hydroxyethylcellulose', 17),
(11, 'Hyper Curling Maskara', 10, 9, NULL, 'images/products/au-maskara-curling.png', 76.00, '2022-12-17', 'Hyper Curling Maskara 2w1 - Among Us 9ml', 'Pomaga w błyskawicznym utrwaleniu rzęs, zapewniając idealne podkręcenie i długotrwały efekt. Aplikator przypominający szczoteczkę do zębów pomaga podkreślić i zagęścić rzęsy. Formuła Swim Proof zapobiega rozmazywaniu i charakteryzuje się wysoką odpornością na wodę, zapewniając delikatny i czysty wygląd rzęs. Szczoteczka typu V-cutting zapewnia mocny efekt utrwalenia, a formuła rozszerzonych włókien mocno rozciągnie rzęsy.', 'Isododecane, trimethylsiloxysilicate, cerecine, bead wax, microcrystalline wax, talc, polypropylsilsesquioxane, dysteadaImmonium hexolite, dextrin palmitate/ethylhexanoate, hydrogenated polyisobutene, propylene carbonate, cellulose, rayon, triethoxycaprylsilane, ethylhexylglycerin, silica, biotin, biotone, biothythia, ethanol, pearl, tocopheno-aminate, silicate,etc', 62),
(12, 'Define Volume Maskara', 10, 9, NULL, 'images/products/au-maskara-volume.png', 76.00, '2022-12-17', 'Define Volume Maskara 2w1 - Among Us 9ml', 'Pomaga w błyskawicznym utrwaleniu rzęs, zapewniając idealne podkręcenie i długotrwały efekt. Aplikator przypominający szczoteczkę do zębów pomaga podkreślić i zagęścić rzęsy. Formuła Swim Proof zapobiega rozmazywaniu i charakteryzuje się wysoką odpornością na wodę, zapewniając delikatny i czysty wygląd rzęs. Pędzel w kształcie zygzaka zapewnia rzęsom odważną objętość dzięki zawartości pudru zwiększającego objętość.', 'Isododecane, trimethylsiloxysilicate, cerecine, bead wax, microcrystalline wax, talc, polypropylsilsesquioxane, dysteadaImmonium hexolite, dextrin palmitate/ethylhexanoate, hydrogenated polyisobutene, propylene carbonate, cellulose, rayon, triethoxycaprylsilane, ethylhexylglycerin, silica, biotin, biotone, biothythia, ethanol, pearl, tocopheno-aminate, silicate,etc', 42),
(13, 'Long Extension Maskara', 10, 9, NULL, 'images/products/au-maskara-extension.png', 76.00, '2022-12-17', 'Long Extension Maskara 2w1 - Among Us 9ml', 'Pomaga w błyskawicznym utrwaleniu rzęs, zapewniając idealne podkręcenie i długotrwały efekt. Aplikator przypominający szczoteczkę do zębów pomaga podkreślić i zagęścić rzęsy. Formuła Swim Proof zapobiega rozmazywaniu i charakteryzuje się wysoką odpornością na wodę, zapewniając delikatny i czysty wygląd rzęs. Zawiera błonnik, który tworzy długie, ale naturalne rzęsy.', 'sododecane, trimethylsiloxysilicate, cerecine, bead wax, microcrystalline wax, talc, polypropylsilsesquioxane, dysteadaImmonium hexolite, dextrin palmitate/ethylhexanoate, hydrogenated polyisobutene, propylene carbonate, cellulose, rayon, triethoxycaprylsilane, ethylhexylglycerin, silica, biotin, biotone, biothythia, ethanol, pearl, tocopheno-aminate, silicate,etc', 38),
(14, 'Maska Rice', 5, 6, NULL, 'images/products/maska-rice.png', 11.00, '2018-05-04', 'Maska do twarzy Rice - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z ryżu. Maska działa wygładzająco i rozświetlająco na skórę.', 'Water, Dipropylene Glycol , Glycerin, Polyglyceryl-10 Laurate, Butylene Glycol, Centella Asiatica Extract , Paeonia Suffruticosa Root Extract , 1,2-Hexanediol, Hydroxyethylcellulose, Acrylates/C10-30 Alkyl Acrylate Crosspolymer , Oryza Sativa (Rice) Extract, Chamomilla Recutita (Matricaria) Flower Extract, Arginine, Glyceryl Caprylate, Ethylhexylglycerin, Glyceryl Acrylate/Acrylic Acid Copolymer , Glycine Max (Soybean) Seed Extract , Propylene Glycol , PVM/MA Copolymer , Citrus Sinensis Peel Oil Expressed , Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Centaurea Cyanus Flower Extract, Pogostemon Cablin Oil, Avandula angustifolia (Lavender) Oil, Disodium EDTA', 15),
(15, 'Maska Mugwort', 5, 6, NULL, 'images/products/maska-mugwort.png', 11.00, '2018-05-04', 'Maska do twarzy Mugwort - Pure Essence', 'Maseczka do twarzy na bawełnianej płachcie. W jej składzie znaleźć można ekstrakt z bylicy pospolitej - tonizuje i działa przeciwzapalnie. Wykazuje właściwości łagodzące podrażnienia, skutecznie odżywia. Pozostawia cerę nawilżoną i ukojoną. Dedykowana dla każdego typu cery, również dla skóry wrażliwej i wymagającej.', 'WATER, GLYCERIN, DIPROPYLENE GLYCOL, BUTYLENE GLYCOL, 1,2-HEXANEDIOL, BETAINE, PANTHENOL, ALLANTOIN, ARTEMISIA PRINCEPS LEAF EXTRACT, SODIUM HYALURONATE, ARGININE, PPG-13-DECYLTETRADECETH-24, CARBOMER, XANTHAN GUM, ETHYLHEXYLGLYCERIN, DISODIUM EDTA, SALVIA OFFICINALIS (SAGE) OIL, SALVIA SCLAREA (CLARY) OIL, JUNIPERUS COMMUNIS FRUIT OIL, MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL, PELARGONIUM GRAVEOLENS FLOWER OIL, BOSWELLIA CARTERII OIL', 15),
(16, 'Maska Damask Rose', 5, 6, NULL, 'images/products/maska-damask-rose.png', 11.00, '2018-05-04', 'Maska do twarzy Damask Rose - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z róży damasceńskiej. Maska działa nawilżająco i rozjaśniająco na skórę.', 'Water, Glycerin, Dipropylene Glycol , Betaine, Polyglyceryl-10 Laurate, Butylene Glycol, Centella Asiatica Extract, Paeonia Suffruticosa Root Extract, 1,2-Hexanediol, Allantoin , Panthenol , Rosa Damascena Extract, Chamomilla Recutita (Matricaria) Flower Extract, Arginine, Carbomer, Glyceryl Caprylate, Xanthan Gum, Ethylhexylglycerin, Punica Granatum Fruit Extract , Pelaronium Graveolens Flower Oil, Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Centaurea Cyanus Flower Extract, Disodium EDTA', 15),
(17, 'Maska Pearl', 5, 6, NULL, 'images/products/maska-pearl.png', 11.00, '2018-05-04', 'Maska do twarzy Pearl - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z pereł. Maska działa rozjaśniająco i wybielająco na skórę.', 'Water, Dipropylene Glycol , Niacinamide , Glycerin, Polyglyceryl-10 Laurate, Butylene Glycol, Paeonia Suffruticosa Root Extract , Centella Asiatica Extract , 1,2-Hexanediol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer , Pearl Extract, Hydroxyethylcellulose, Chamomilla Recutita (Matricaria) Flower Extract, Arginine, Glyceryl Caprylate, Ethylhexylglycerin, Glyceryl Acrylate/Acrylic Acid Copolymer , Honey Extract, Sodium Hyaluronate, PVM/MA Copolymer , Propylene Glycol , Citrus Sinensis Peel Oil Expressed, Lavandula Angustifolia (Lavender) Flower Extract, Viola Tricolor Extract, Centaurea Cyanus Flower Extract, Citrus Aurantium Dulcis (Orange) Peel Oil , Pogostemon Cablin Oil, Disodium EDTA', 15),
(18, 'Maska Acai Berry', 5, 6, NULL, 'images/products/maska-acai-berry.png', 11.00, '2018-05-04', 'Maska do twarzy Acai Berry - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z jagód acai. Maska działa odżywczo, rewitalizująco i przeciwzmarszczkowo.', 'Water, Dipropylene Glycol , Glycerin, Polyglyceryl-10 Laurate , Butylene Glycol, Centella Asiatica Extract , Paeonia Suffruticosa Root Extract , 1,2-Hexanediol, Hydroxyethylcellulose, Chamomilla Recutita (Matricaria) Flower Extract, Euterpe Oleracea Fruit Extract, Glyceryl Caprylate, Arginine, Carbomer, Ethylhexylglycerin, Xanthan Gum , Allantoin , Nelumbo Nucifera Flower Extract, Sodium Hyaluronate, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Citrus Aurantium Dulcis (Orange) Peel Oil , Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Lavandula Angustifolia (Lavender) Oil, Centaurea Cyanus Flower Extract, Eucalyptus Globulus Leaf Oil, Disodium EDTA', 35),
(19, 'Maska Green Tea', 5, 6, NULL, 'images/products/maska-green-tea.png', 11.00, '2018-05-04', 'Maska do twarzy Green Tea - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z zielonej herbaty. Maska działa intensywnie nawilżająco na skórę.', 'Water, Glycerin, Dipropylene Glycol , Betaine, Polyglyceryl-10 Laurate, Butylene Glycol, Centella Asiatica Extract, Paeonia Suffruticosa Root Extract, 1,2-Hexanediol, Allantoin , Panthenol , Chamomilla Recutita (Matricaria) Flower Extract, Camellia Sinensis Leaf Extract , Arginine, Carbomer, Glyceryl Caprylate, Xanthan Gum, Ethylhexylglycerin, Citrus Aurantium Bergamia (Bergamot) Peel Oil , Artemisia Vulgaris Extract, Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Centaurea Cyanus Flower Extract, Madecassoside, Disodium EDTA', 27),
(20, 'Maska Lemon', 5, 6, NULL, 'images/products/maska-lemon.png', 11.00, '2018-05-04', 'Maska do twarzy Lemon - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z cytryny. Maska działa oczyszczająco i rozjaśniająco na skórę.', 'Water, Glycerin, Dipropylene Glycol , Betaine, Polyglyceryl-10 Laurate, Butylene Glycol, Centella Asiatica Extract, Paeonia Suffruticosa Root Extract, 1,2-Hexanediol, Allantoin , Panthenol , Citrus Limon (Lemon) Fruit Extract, Chamomilla Recutita (Matricaria) Flower Extract, Arginine, Carbomer, Glyceryl Caprylate, Xanthan Gum, Ethylhexylglycerin, Citrus Aurantium Dulcis (Orange) Oil, Pyrus Malus (Apple) Fruit Extract , Carica Papaya (Papaya) Leaf Extract, Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Centaurea Cyanus Flower Extract, Disodium EDTA', 13),
(21, 'Maska Shea Butter', 5, 6, NULL, 'images/products/maska-shea-butter.png', 11.00, '2018-05-04', 'Maska do twarzy Shea Butter - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera masło shea. Maska działa odżywczo i nawilżająco na skórę.', 'Water, Dipropylene Glycol , Glycerin, Polyglyceryl-10 Laurate , Butylene Glycol, Centella Asiatica Extract , Paeonia Suffruticosa Root Extract , 1,2-Hexanediol, Hydroxyethylcellulose, Chamomilla Recutita (Matricaria) Flower Extract, Glyceryl Caprylate, Arginine, Carbomer, Ethylhexylglycerin, Xanthan Gum , Allantoin , Sodium Hyaluronate, Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Citrus Aurantium Dulcis (Orange) Peel Oil , Centaurea Cyanus Flower Extract, Citrus Paradisi (Grapefruit) Peel Oil , Lavandula Angustifolia (Lavender) Oil, Butyrospermum Parkii (Shea) Butter, Oryza Sativa (Rice) Bran Oil , Boswellia Carterii Oil , Pelargonium Graveolens Flower Oil, Vetiveria Zizanoides Root Oil, Disodium EDTA', 17),
(22, 'Maska Cucumber', 5, 6, NULL, 'images/products/maska-cucumber.png', 11.00, '2018-05-04', 'Maska do twarzy Cucumber - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z ogórka. Maska działa intensywnie nawilżająco na skórę.', 'Water, Glycerin, Dipropylene Glycol , Betaine, Polyglyceryl-10 Laurate, Butylene Glycol, Centella Asiatica Extract, Paeonia Suffruticosa Root Extract, 1,2-Hexanediol, Allantoin , Panthenol , Chamomilla Recutita (Matricaria) Flower Extract, Cucumis Sativus (Cucumber) Fruit Extract , Arginine, Carbomer, Glyceryl Caprylate, Xanthan Gum, Ethylhexylglycerin, Aloe Barbadensis Leaf Extract, Aniba Rosaeodora (Rosewood) Wood Oil , Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Centaurea Cyanus Flower Extract, Disodium EDTA', 19),
(23, 'Maska Avocado', 5, 6, NULL, 'images/products/maska-avocado.png', 11.00, '2018-05-04', 'Maska do twarzy Avocado - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z avocado. Maska działa przeciwzmarszczkowo i poprawia elastyczność skóry.', 'Water, Dipropylene Glycol , Glycerin, Polyglyceryl-10 Laurate , Butylene Glycol, Centella Asiatica Extract , Paeonia Suffruticosa Root Extract , 1,2-Hexanediol, Hydroxyethylcellulose, Chamomilla Recutita (Matricaria) Flower Extract, Persea Gratissima (Avocado) Fruit Extract, Glyceryl Caprylate, Arginine, Carbomer, Adenosine, Ethylhexylglycerin, Xanthan Gum , Allantoin , Milk Protein Extract, Sodium Hyaluronate, Citrus Aurantium Dulcis (Orange) Peel Oil , Olea Europaea (Olive) Fruit Oil, Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Centaurea Cyanus Flower Extract, Avandula angustifolia (Lavender) Oil, Ocimum Basilicum (Basil) Oil, Pelargonium Graveolens Flower Oil, Disodium EDTA', 21),
(24, 'Maska Strawberry', 5, 6, NULL, 'images/products/maska-strawberry.png', 11.00, '2018-05-04', 'Maska do twarzy Strawberry - Pure Essence', 'Maseczka do twarzy w formie bawełnianego płatu. Produkt zawiera ekstrakt z truskawek. Maska działa intensywnie nawilżająco na skórę.', 'Water, Dipropylene Glycol , Glycerin, Polyglyceryl-10 Laurate, Butylene Glycol, Centella Asiatica Extract , Paeonia Suffruticosa Root Extract , 1,2-Hexanediol, Hydroxyethylcellulose, Acrylates/C10-30 Alkyl Acrylate Crosspolymer , Fragaria Chiloensis (Strawberry) Fruit Extract , Chamomilla Recutita (Matricaria) Flower Extract, Arginine, Glyceryl Caprylate, Ethylhexylglycerin, Glyceryl Acrylate/Acrylic Acid Copolymer , Citrus Junos Fruit Extract, Propylene Glycol , PVM/MA Copolymer , Citrus Aurantium Dulcis (Orange) Peel Oil , Viola Tricolor Extract, Lavandula Angustifolia (Lavender) Flower Extract, Centaurea Cyanus Flower Extract, Citrus Tangerina (Tangerine) Peel Oil , Litsea Cubeba Fruit Oil, Myristica Fragrans (Nutmeg) Kernel Oil , Disodium EDTA', 12),
(25, 'Maska Charcoal', 5, 6, NULL, 'images/products/maska-charcoal.png', 11.00, '2018-05-04', 'Maska do twarzy Charcoal - Pure Essence', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt jest nasycony ekstraktem z węgla. Sprawdzi się w pielęgnacji cery tłustej i mieszanej. Węgiel wpływa na usunięcie nadmiaru sebum ze skóry.', 'Water, Dipropylene Glycol, Glycerin, Betaine, Polyglyceryl-10 Laurate, Butylene Glycol, Paeonia Suffruticosa Root Extract, Centella Asiatica Extract, 1,2-Hexanediol, Carbomer, Arginine, Chamomilla Recutita (Matricaria) Flower Extract, Panthenol, Glyceryl Caprylate, Xanthan Gum, Ethylhexylglycerin, Allantoin, Citrus Aurantium Bergamia (Bergamot) Fruit Oil, Pueraria Lobata Root Extract, Ulmus Davidiana Root Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Pinus Palustris Leaf Extract, Sodium Hyaluronate, Charcoal Powder, Disodium EDTA', 9),
(26, 'Maska Honey Acerola', 5, 8, NULL, 'images/products/honey-acerola.png', 99.90, '2019-03-27', 'Honey Sleeping Pack Całonocna Maseczka Acerola 90ml', 'Maseczka zawiera miód i wyciąg z owoców z Aceroli. Produkt odżywia, nawilża i ujędrnia skórę. Maseczka przeznaczona do skóry dojrzałej i pozbawionej jędrności. Produkt redukuje pierwsze oznaki starzenia, działa przeciwzmarszczkowo.', 'Water, Disodium EDTA, Honey Extract, Malpighia Glabra (Acerola) Fruit Extract, Glycerin, Methylparaben, Carbomer, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Dipotassium Glycyrrhizate , Dimethicone, Arginine, Glycereth-26, Phenoxyethanol, Ethanol, PEG-2M, PEG-90M , My Asia Beauty, Hydrogenated Lecithin, Sucrose Distearate, Dipropylene Glycol, Portulaca Oleracea Extract, Caramel, CI 19140, CI 17200, Fragrance', 28),
(27, 'Maska Honey Canola', 5, 8, NULL, 'images/products/honey-canola.png', 99.90, '2019-03-27', 'Honey Sleeping Pack Całonocna Maseczka Canola 90ml', 'Maseczka zawiera miód, olej Canola i ekstrakt z portulaki pospolitej. Produkt przeznaczony do skóry suchej, zmęczonej i szarej. Maseczka redukuje oznaki starzenia, ujędrnia i uelastycznia skórę. Produkt dogłębnie nawilża skórę i utrzymuje odpowiedni poziom nawodnienia.', 'Water, Disodium EDTA, Honey Extract, Brassica Campestris (Rapeseed) Extract, Glycerin, Methylparaben, Carbomer, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, My Asia Beauty, Dipotassium Glycyrrhizate, Dimethicone, Arginine, Glycereth-26, Phenoxyethanol, Ethanol, PEG-2M, PEG-90M, Hydrogenated Lecithin, Sucrose Distearate, Dipropylene Glycol, Portulaca Oleracea Extract, CI 15985 , CI 19140 , Fragrance', 31),
(28, 'Maska Honey Blueberry', 5, 8, NULL, 'images/products/honey-blueberry.png', 99.90, '2019-03-27', 'Honey Sleeping Pack Całonocna Maseczka Blueberry 90ml', 'Maseczka zawiera miód i wyciąg z czarnej jagody. Produkt przeznaczony do skóry tłustej, z rozszerzonymi porami i niedoskonałościami. Maseczka działa kojąco i łagodząco na skórę, przyspiesza gojenie zmian trądzikowych. Produkt zmniejsza widoczność porów, wygładza i zmiękcza skórę.', 'Woda, gliceryna, dimetikon, glikol butylenowy, 1,2-heksanodiol, gliceryna-26, ekstrakt z miodu, ekstrakt z owoców Vaccinium Angustifolium (borówka), arginina, uwodorniony izostearynian oleju rycynowego, karbomer, uwodorniona lecytyna, akrylany/C10-30 alkiloakrylanowy polimer krzyżowy , PEG-2M, distearynian sacharozy, glicyryzynian dipotasowy, ekstrakt Portulaca Oleracea, poliakrylan sodu, EDTA disodowy, karmel, CI 15985, CI 17200, etyloheksylogliceryna, zapach', 12),
(29, 'Pianka Rice', 2, 4, NULL, 'images/products/pianka-rice.png', 34.90, '2021-06-15', 'Rice rozjaśniająca pianka do twarzy - Daily Fresh 150ml', 'Holika Holika Rice Rozjaśniająca pianka do twarzy 150ml to produkt przeznaczony do oczyszczania skóry twarzy, zwłaszcza szarej i zmęczonej. Pianka usuwa zanieczyszczenia, oczyszcza pory i wygładza skórę. Produkt zawiera ekstrakt z ryżu o właściwościach przeciwzmarszczkowych, rozjaśniających i wygładzających.', 'Water, Stearic Acid, Glycerin, Lauric Acid, Potassium Hydroxide, Myristic Acid, Glyceryl Stearate, PEG-100 Stearate, Cocamidopropyl Betaine, PEG-8, Polyquaternium-7, Polysorbate 20, Hydroxyethylcellulose, Sodium Chloride, Rice Ferment Filtrate (Sake), Saponaria Officinalis Leaf Extract, Butylene Glycol, 1,2-Hexanediol, Phenoxyethanol, Fragrance', 3),
(30, 'Pianka Green Tea', 2, 4, NULL, 'images/products/pianka-green-tea.png', 34.90, '2021-06-15', 'Green Tea oczyszczająca pianka do twarzy - Daily Fresh 150ml', 'Holika Holika Green Tea Oczyszczająca pianka do twarzy 150ml to produkt przeznaczony do oczyszczania skóry twarzy, zwłaszcza tłustej i problemowej. Produkt oczyszcza pory, usuwa zanieczyszczenia i pozostawia skórę świeżą. Pianka zawiera ekstrakt z zielonej herbaty o właściwościach przeciwbakteryjnych.', 'WATER, STEARIC ACID, GLYCERIN, LAURIC ACID, POTASSIUM HYDROXIDE, MYRISTIC ACID, GLYCERYL STEARATE, PEG-100 STEARATE, COCAMIDOPROPYL BETAINE, PEG-8, POLYQUATERNIUM-7, POLYSORBATE 20, HYDROXYETHYLCELLULOSE, SODIUM CHLORIDE, CAMELLIA SINENSIS LEAF EXTRACT, SAPONARIA OFFICINALIS LEAF EXTRACT, BUTYLENE GLYCOL, CI 19140, CI 42090, PHENOXYETHANOL, FRAGRANCE', 9),
(31, 'Pianka Citron', 2, 4, NULL, 'images/products/pianka-citron.png', 34.90, '2021-06-15', 'Citron złuszczająca pianka do twarzy - Daily Fresh 150ml', 'Masz skórę mieszaną czy tłustą? Doświadcz wspaniałego uczucia miękkiej i świeżej skóry. Pianka oczyszczająca Holika Holika Daily Fresh Citron usuwa ze skóry zanieczyszczenia i makijaż. Dzięki ekstraktowi z cytryny, bogatemu w witaminę C i kwas jabłkowy, nie tylko usuwa martwe komórki naskórka, ale także wygładza drobne zmarszczki i przywraca skórze zdrowy koloryt i naturalny blask.', 'WATER, STEARIC ACID, GLYCERIN, LAURIC ACID, POTASSIUM HYDROXIDE, MYRISTIC ACID, GLYCERYL STEARATE, PEG-100 STEARATE, COCAMIDOPROPYL BETAINE, PEG-8, POLYQUATERNIUM-7, POLYSORBATE 20, HYDROXYETHYLCELLULOSE, SODIUM CHLORIDE, CITRUS JUNOS SEED OIL, SAPONARIA OFFICINALIS LEAF EXTRACT, BUTYLENE GLYCOL, TOCOPHERYL ACETATE, CI 19140, PHENOXYETHANOL, FRAGRANCE', 65),
(32, 'Pianka Olive', 2, 4, NULL, 'images/products/pianka-olive.png', 34.90, '2021-06-15', 'Olive oczyszczająca pianka do twarzy - Daily Fresh 150ml', 'Nadaje się do każdego rodzaju skóry, szczególnie do skóry suchej. Pianka jest skutecznym narzędziem do oczyszczania skóry, usuwa codzienne zabrudzenia, ślady makijażu. Nadaje skórze gładkość, miękkość i świeżość, nie zatyka porów. Produkt zawiera sfermentowany ekstrakt z oliwek, który działa odmładzająco, może zapobiegać powstawaniu zmarszczek i wygładzać już istniejące. Zawiera dużą ilość przeciwutleniaczy i witaminę E. Witamina ta pomaga organizmowi lepiej wchłaniać witaminy A, D, K i zapobiega blaknięciu komórek.', 'Water, Stearic Acid, Glycerin, Lauric Acid, Potassium Hydroxide, Myristic Acid, Glyceryl Stearate, PEG-100 Stearate, Cocamidopropyl Betaine, PEG-8, Polyquaternium-7, Polysorbate 20, Hydroxyethylcellulose, Sodium Chloride, Olea Europaea (Olive) Fruit Oil, Saponaria Officinalis Leaf Extract, Butylene Glycol, CI 19140, CI 15985, Phenoxyethanol, Fragrance', 70),
(33, 'Pianka Bamboo', 2, 4, NULL, 'images/products/pianka-bamboo.png', 39.90, '2021-06-15', 'Bamboo łagodząca pianka do Twarzy - Daily Fresh 150ml', 'Produkt przeznaczony do oczyszczania skóry twarzy. Pianka skutecznie usuwa zanieczyszczenia, oczyszcza pory i wygładza skórę. Produkt zawiera ekstrakt z bambusa, który posiada właściwości nawilżające, kojące oraz łagodzące. Wzmacnia ściany naczyń krwionośnych, zapobiegając ich pękaniu (zmniejsza tendencję do rozszerzonych naczynek).', 'Aqua, Stearic Acid, Glycerin, Lauric Acid, Potassium Hydroxide, Myristic Acid, Glyceryl Stearate, PEG-100 Stearate, Cocamidopropyl Betaine, PEG-8, Polyquaternium-7, Polysorbate 20, Hydroxyethylcellulose, Sodium Chloride, Bambusa Vulgaris Leaf/Stem Extract, Saponaria Officinalis Leaf Extract, Butylene Glycol, 1,2-Hexanediol, CI 19140, CI 42090, Phenoxyethanol, Parfum', 52),
(34, 'Tangerine 96%', 1, NULL, NULL, 'images/products/96-tangerine.png', 50.50, '2022-11-22', 'Żel kojąco nawilżający z mandarynką 390ml', 'Jak dbać o skórę poparzoną słońcem, przegrzaną lub wrażliwą? Nawilżająco-łagodzący żel z mandarynką Holika Holika Tangerine przyniesie Ci szybką ulgę podczas wahań temperatury, po opalaniu lub odwodnieniu. Kompleks mandarynkowy łagodzi suchą i wrażliwą skórę, a kompleks AHA usuwa martwe komórki naskórka. O regenerację dbają ekstrakty owocowe, aloes i trzcina cukrowa. Delikatny żel natychmiast się wchłania i pozostawia skórę miękką, gładką i chronioną.', 'ALOE BARBADENSIS LEAF JUICE,  NELUMBIUM SPECIOSUM FLOWER EXTRACT,  CENTELLA ASIATICA EXTRACT,  BAMBUSA VULGARIS EXTRACT,  CUCUMIS SATIVUS (CUCUMBER) FRUIT EXTRACT,  ZEA MAYS (CORN) LEAF EXTRACT,  BRASSICA OLERACEA CAPITATA (CABBAGE) LEAF EXTRACT,  CITRULLUS LANATUS (WATERMELON) FRUIT EXTRACT,  PEG-60 HYDROGENATED CASTOR OIL,  SODIUM POLYACRYLATE, CARBOMER,  TRIETHANOLAMINE,  FRAGRANCE,  PHENOXYETHANOL', 11),
(35, 'Watermelon 96%', 1, NULL, NULL, 'images/products/96-watermelon.png', 50.50, '2022-11-23', 'Żel intensywnie nawilżający odświeżający cerę 390ml', 'W upalne letnie dni na pewno chętnie zkorzystasz z odświeżanie, jednak nadal trzeba dbać również o nawilżenie. Z myślą o takich warunkach powstał właśnie żel do intensywnego nawodnienia i odświeżenia skóry Holika Holika Watermelon 96%. Jego specjalna formuła oparta na arbuzie zapewnia obfite nawilżenie i odżywienie skóry, na dodatek ją również uelastycznia i zmiękcza. Dzięki ochronie wrażliwej skóry przed zewnętrznymi podrażnieniami możesz cieszyć się długotrwałymi efektami i piękną cerą.', 'CITRULLUS LANATUS (WATERMELON) FRUIT EXTRACT, BUTYLENE GLYCOL, 1,2-HEXANEDIOL, GLYCERETH-26, WATER, ALLANTOIN, PANTHENOL, ALOE BARBADENSIS LEAF EXTRACT, DIOSCOREA JAPONICA ROOT EXTRACT, LAMINARIA JAPONICA EXTRACT, PORTULACA OLERACEA EXTRACT, GLYCERIN, PROPANEDIOL, ECTOIN, CENTELLA ASIATICA EXTRACT, FRAGARIA CHILOENSIS (STRAWBERRY) FRUIT EXTRACT, PUNICA GRANATUM FRUIT EXTRACT, PYRUS MALUS (APPLE) FRUIT EXTRACT, SCHIZANDRA CHINENSIS FRUIT EXTRACT, SOLANUM LYCOPERSICUM (TOMATO) FRUIT EXTRACT, SAUSSUREA INVOLUCRATA EXTRACT, CARBOMER, PEG-60 HYDROGENATED CASTOR OIL, TROMETHAMINE, DISODIUM EDTA, BUTETH-3, SODIUM BENZOTRIAZOLYL BUTYLPHENOL SULFONATE, TRIBUTYL CITRATE, ETHYLHEXYLGLYCERIN, CI 17200, CI 19140, PHENOXYETHANOL, FRAGRANCE', 14),
(36, 'Płatki pod oczy Avocado', 1, NULL, NULL, 'images/products/platki-avocado.png', 160.00, '2023-07-12', 'Eyefessional Płatki pod oczy Antiwrinkle Avocado 60 sztuk', 'Żelowe, delikatne płatki dedykowane wymagającej skórze pod oczami. Dokładnie nawilżają i odżywiają podrażnione i suche miejsca. W wersji Avocado, wykazują właściwości przeciwzmarszczkowe i ujędrniające. Hydrożelowe płatki najlepiej aplikować na 20-30 minut.', 'WATER, GLYCERIN, CHONDRUS CRISPUS EXTRACT, CERATONIA SILIQUA (CAROB) GUM, PERSEA GRATISSIMA (AVOCADO) FRUIT EXTRACT(10,000 ppm), 1,2-HEXANEDIOL, CELLULOSE GUM, PENTYLENE GLYCOL, POTASSIUM CHLORIDE, BUTYLENE GLYCOL, ALLANTOIN, XANTHAN GUM, ETHYLHEXYLGLYCERIN, ADENOSINE, GARDENIA FLORIDA FRUIT EXTRACT, SUCROSE, TITANIUM DIOXIDE, DISODIUM EDTA, DEXTRIN, CALCIUM LACTATE, POLYGLYCERYL-6 CAPRYLATE, POLYGLYCERYL-4 CAPRATE, LACTOBACILLUS FERMENT, SODIUM POLYACRYLOYLDIMETHYL TAURATE, COLLAGEN EXTRACT, HYDROLYZED ELASTIN, FRAGRANCE, BUTYROSPERMUM PARKII (SHEA) BUTTER, TOCOPHEROL, SODIUM HYALURONATE', 25),
(37, 'Płatki pod oczy Aloe', 1, NULL, NULL, 'images/products/platki-aloe.png', 160.00, '2023-07-12', 'Eyefessional Płatki pod oczy Calming Aloe 60 sztuk', 'Eyefressional Cool Calming Aloe Eye Patch zawierają sok z aloesu, który tworzy nawilżający film na powierzchni skóry oraz zmiękcza i regeneruje. Ma silne działanie lecznicze i kojące, poprawia elastyczność skóry, a także dostarcza witamin i minerałów, chroniąc skórę przed szkodliwym działaniem środowiska.', 'Water(Aqua), Glycerin, Chondrus Crispus Extract, Ceratonia Siliqua (Carob) Gum, Aloe Barbadensis Leaf Juice, 1,2-Hexanediol, Cellulose Gum, Pentylene Glycol, Potassium Chloride, Allantoin,Xanthan Gum, Ethylhexylglycerin, Sucrose, Disodium EDTA, Calcium Lactate, Collagen Extract, Polyglyceryl-6 Caprylate, Polyglyceryl-4 Caprate, Hydrolyzed Elastin, Chromium Oxide Greens (CI 77288), Butylene Glycol,Laminaria Japonica Extract,Ulmus Davidiana Root Extract, Aloe Barbadensis Leaf Extract, Viola Mandshurica Flower Extract, Dioscorea Japonica Root Extract, Tocopherol, Sodium Hyaluronate, Sodium Polyacryloyldimethyl Taurate, Sodium Citrate, Fragrance(Parfum), Citric Acid', 25),
(38, 'Płatki pod oczy Tangerine', 1, NULL, NULL, 'images/products/platki-tangerine.png', 160.00, '2023-07-12', 'Eyefessional Płatki pod oczy Brightening Tangerine 60 sztuk', 'Żelowe, delikatne płatki dedykowane wymagającej skórze pod oczami. Dokładnie nawilżają i odżywiają podrażnione i suche miejsca. W wersji Tangerine, wykazują właściwości rozświetlające i rozjaśniające. Hydrożelowe płatki najlepiej aplikować na 20-30 minut.', 'WATER, GLYCERIN, NIACINAMIDE, CHONDRUS CRISPUS EXTRACT, CITRUS TANGERINA (TANGERINE) EXTRACT(10,000 ppm), CERATONIA SILIQUA (CAROB) GUM, CELLULOSE GUM, 1,2-HEXANEDIOL, PENTYLENE GLYCOL SUCROSE POTASSIUM CHLORIDE, ALLANTOIN, DIPOTASSIUM GLYCYRRHIZATE, XANTHAN GUM, ETHYLHEXYLGLYCERIN, BUTYLENE GLYCOL, HYDROLYZED ELASTIN, GARDENIA FLORIDA FRUIT EXTRACT, DISODIUM EDTA, CALCIUM LACTATE, DEXTRIN, SODIUM POLYACRYLOYLDIMETHYL TAURATE, POLYGLYCERYL-6 CAPRYLATE, POLYGLYCERYL-4 CAPRATE HYDROLYZED COLLAGEN, FRAGRANCE, CITRUS LIMON (LEMON) FRUIT EXTRACT, MALPIGHIA GLABRA (ACEROLA) FRUIT EXTRACT, MYRCIARIA DUBIA FRUIT EXTRACT, HYALURONIC ACID, TOCOPHEROL, HYDROLYZED HYALURONIC ACID ASCORBYL GLUCOSIDE, SODIUM HYALURONATE.', 25),
(39, 'Płatki pod oczy Cica', 1, NULL, NULL, 'images/products/platki-cica.png', 160.00, '2023-07-12', 'Eyefessional Płatki pod oczy Calming Cica 60 sztuk', 'Żelowe, delikatne płatki dedykowane wymagającej skórze pod oczami. Dokładnie nawilżają i odżywiają podrażnione i suche miejsca. W wersji Calming Cica, wykazują właściwości łagodzące i kojące. Hydrożelowe płatki najlepiej aplikować na 20-30 minut.', 'Water (Aqua), Glycerin, Chondrus Crispus Extract, Ceratonia Siliqua (Carob) Gum, 1,2-Hexanediol, Cellulose Gum, Pentylene Glycol,Potassium Chloride, Allantoin, Xanthan Gum, Ethylhexylglycerin, Centella Asiatica Extract, Centella Asiatica Leaf Extract, Sucrose, Disodium EDTA, Calcium Lactate, Polyglyceryl-6 Caprylate, Polyglyceryl-4 Caprate, Dipotassium Glycyrrhizate, Sodium Polyacryloyldimethyl Taurate, Butylene Glycol, Fragrance(Parfum), Caprylic/Capric Triglyceride, Hydrogenated Phosphatidylcholine, Hydrolyzed Elastin, Sucrose Stearate, Tocopherol, Cetearyl Alcohol, Sodium Hyaluronate, Collagen Extract, Madecassoside, Madecassic Acid, Asiaticoside, Asiatic Acid', 25),
(40, 'Maska After Hard Study', 5, 7, NULL, 'images/products/maska-after-study.png', 12.00, '2018-02-17', 'Maska do twarzy - After Hard Study', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt z serii: After Mask Sheet. Maska zawiera ekstrakty: zielonej herbaty i olejku z drzewa herbacianego. Produkt posiada właściwości: łagodzące, oczyszczające, regenerujące i relaksujące.', 'Water, Glycerin, Alcohol, PEG-60 Hydrogenated Castor Oil, Phenoxyethanol, Carbomer, Triethanolamine, Melaleuca Alternifolia (Tea Tree) Extract, Camellia Sinensis Leaf Extract, Calendula Officinalis Flower Extract, Hamamelis Virginiana (Witch Hazel) LeafExtract, Allantoin, Disodium EDTA, Fragrance, Sodium Hyaluronate, Trehalose', 10),
(41, 'Maska After Trip', 5, 7, NULL, 'images/products/maska-after-trip.png', 12.00, '2018-02-17', 'Maska do twarzy - After Trip', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt z serii: After Mask Sheet. Maska zawiera ekstrakty: pomidora, kokosu, pomarańczy. Produkt posiada właściwości: rozjaśniające, nawilżające, regenerujące i relaksujące.', 'Water, Glycerin, Alcohol, PEG-60 Hydrogenated Castor Oil, Phenoxyethanol, Carbomer, Triethanolamine, Solanum Lycopersicum (Tomato) FruitExtract, Actinidia Chinensis (Kiwi) Fruit Extract, Citrus Aurantium Dulcis (Orange) PeelExtract, Cocos Nucifera (Coconut) Fruit Extract, Allantoin, Disodium EDTA, Fragrance, Sodium Hyaluronate, Trehalose', 12),
(42, 'Maska After Working Out', 5, 7, NULL, 'images/products/maska-after-working-out.png', 12.00, '2018-02-17', 'Maska do twarzy - After Working Out', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt z serii: After Mask Sheet. Maska zawiera ekstrakty: aloesu, miodu, ziemniaka i bamabusa. Produkt posiada właściwości: łagodzące, kojące, regenerujące i relaksujące.', 'Water, Glycerin, Alcohol, PEG-60 Hydrogenated Castor Oil, Phenoxyethanol, Carbomer, Triethanolamine, Aloe Barbadensis Leaf Extract, Solanum Tuberosum (Potato) Pulp Extract, Bambusa Vulgaris Extract, Honey Extract, Allantoin, Disodium EDTA, Fragrance, Sodium Hyaluronate, Trehalose', 13),
(43, 'Maska After Working Overtime', 5, 7, NULL, 'images/products/maska-after-working-overtime.png', 12.00, '2018-02-17', 'Maska do twarzy - After Working Overtime', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt z serii: After Mask Sheet. Maska zawiera ekstrakty: mięty, rumianku, aceroli i czarnych jagód. Produkt posiada właściwości: odżywcze, rewitalizujące, regenerujące i relaksujące.', 'Water, Glycerin, Alcohol, PEG-60 Hydrogenated Castor Oil, Phenoxyethanol, Carbomer, Triethanolamine, Mentha Piperita (Peppermint) Leaf Extract, Chamomilla Recutita (Matricaria) FlowerExtract, Malpighia Emarginata (Acerola) Fruit Extract, Vaccinium Angustifolium (Blueberry) FruitExtract, Allantoin, Disodium EDTA, Fragrance, Sodium Hyaluronate, Trehalose', 11),
(44, 'Maska After Quarantine', 5, 7, NULL, 'images/products/maska-after-quarantine.png', 12.00, '2018-02-17', 'Maska do twarzy - After Quarantine', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt z serii: After Mask Sheet. Doskonale uzupełnia codzienną pielęgnację, pozostawiając skórę nawilżoną i odświeżoną. Maseczka idealnie sprawdzi się w przypadku posiadania skóry wrażliwej.', 'Water, Glycerin, Alcohol Denat,, 1,2-Hexanediol, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Panthenol, Palmitoyl Pentapeptide-4, Chamaecyparis Obtusa Water, Aloe Barbadensis Leaf Juice, Glycyrrhiza Glabra (Licorice) Root Extract, Anthemis Nobilis Flower Water, Centella Asiatica Extract, Trehalose, Rosmarinus Officinalis (Rosemary) Leaf Oll, Polyglyceryl-10 Laurate, Carbomer, Tromethamine, Allantoin, Disodium Edta, Glyceryl Caprylate, Ethylhexylglycerin', 9),
(45, 'Maska After Drinking', 5, 7, NULL, 'images/products/maska-after-drinking.png', 12.00, '2018-02-17', 'Maska do twarzy - After Drinking', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt z serii: After Mask Sheet. Maska zawiera ekstrakty: mięty, rumianku, aceroli i czarnych jagód. Produkt posiada właściwości: odświeżające, oczyszczające, regenerujące i relaksujące.', 'Water, Glycerin, Alcohol, PEG-60 Hydrogenated Castor Oil, Phenoxyethanol, Carbomer, Triethanolamine, Camellia Sinensis Leaf Extract, Rosa Canina Flower Extract, Brassica Oleracea Capitata (Cabbage)Leaf Extract, Hovenia Dulcis Fruit Extract, Allantoin, Disodium EDTA, Fragrance, Sodium Hyaluronate, Trehalose', 6),
(46, 'Maska After Sauna', 5, 7, NULL, 'images/products/maska-after-sauna.png', 12.00, '2018-02-17', 'Maska do twarzy - After Sauna', 'Maseczka do twarzy w formie bawełnianej płachty. Produkt z serii: After Mask Sheet. Maska zawiera ekstrakty: z mięty, kasztanów, ogórka oraz limonki. Produkt posiada właściwości: oczyszczające, odświeżające i zmniejszające pory.', 'Water, Glycerin, Alcohol, PEG-60 Hydrogenated Castor Oil, Phenoxyethanol, Carbomer, Triethanolamine, Mentha Rotundifolia Leaf Extract, Castanea Crenata (Chestnut) Shell Extract, Cucumis Sativus (Cucumber) Fruit Extract, Citrus Aurantifolia (Lime) Fruit Extract, Allantoin, Disodium EDTA, Fragrance, Sodium Hyaluronate, Trehalose', 21),
(47, 'Mydełko Red Clay Egg Soap', 2, 3, NULL, 'images/products/mydelko-red-clay.png', 49.00, '2021-05-25', 'Mydełko do twarzy Red Clay Egg Soap', 'Produkt przeznaczony do pielęgnacji i oczyszczania twarzy. Mydełko w formie 2 jajeczek w opakowaniu. Produkt oczyszcza skórę, zwęża pory, niweluje zaskórniki. Mydełko zawiera: proteiny, glinkę kaolin, lecytynę.', 'Sekken Soji, Loess, Glycerin, Vitis Vinifera (Grape) Seed Oil, Butyrospermum Parkii (Shea) Butter, Aloe Barbadensis Leaf Extract, Tocopherol, Fragrance', 17),
(48, 'Mydełko Green Tea Egg Soap', 2, 3, NULL, 'images/products/mydelko-green-tea.png', 49.00, '2021-05-25', 'Mydełko do twarzy Egg Soap', 'Produkt przeznaczony do pielęgnacji i oczyszczania twarzy. Mydełko w formie 2 jajeczek w opakowaniu, zawiera ekstrakt z zielonej herbaty. Produkt oczyszcza skórę, zwęża pory, niweluje zaskórniki. Mydełko przeznaczone do pielęgnacji cery tłustej i trądzikowej.', 'Myristic Acid, Stearic Acid, Triethanolamine, Lauric Acid, Sodium Lauryl Sulfate, Palmitic Acid, Glycerine, Purified Water, Sodium Hydroxide, Disodium Lauryl Sulfosuccinate, Perfume, Hydrolyzed Egg Protein (Eggs White), Camellia Sinensis Leaf (Green Tea) Extract, Triclosan, Titanium Dioxide, Tetrasodium EDTA (EDTA-4NA)', 16),
(49, 'Mydełko White Egg Soap', 2, 3, NULL, 'images/products/mydelko-.png', 49.00, '2021-05-25', 'Mydełko do twarzy Egg Soap', 'Produkt przeznaczony do pielęgnacji i oczyszczania twarzy. Mydełko w formie 2 jajeczek w opakowaniu. Odpowiednie dla każdego rodzaju skóry, białe mydło pomaga odblokować pory z brudu i bakterii, poprawiając ich wygląd i poprawiając wygląd skóry.', 'Myristic Acid, Stearic Acid, Triethanolamine, Lauric Acid, Palmitic Acid, Glycerine, Purified Water, Sodium Hydroxide, Disodium Lauryl Sulfosuccinate, Perfume, Hydrolyzed Egg Protein (Eggs White), Triclosan, Titanium Dioxide, Tetrasodium EDTA(EDTA-4NA)', 32);
INSERT INTO `cosmetics` (`ID`, `name`, `id_type1`, `id_type2`, `id_type3`, `img`, `price`, `date`, `shortDescription`, `description`, `ingredients`, `quantity`) VALUES
(50, 'Mydełko Charcoal Egg Soap', 2, 3, NULL, 'images/products/mydelko-charcoal.png', 49.00, '2021-05-25', 'Mydełko do twarzy Egg Soap', 'Produkt głęboko oczyszcza skórę twarzy, odblokowując pory. Dzięki długotrwałemu stosowaniu może delikatnie rozjaśnić skórę, wyrównując koloryt. Produkt odpowiedni jest do skóry problematycznej, tłustej, mieszanej oraz trądzikowej z licznymi przebarwieniami. Działa zarówno jako mydło oczyszczające, jak i maseczka.', 'Sekken Soji, Charcoal Powder, Glycerin, Vitis Vinifera (Grape) Seed Oil, Butyrospermum Parkii (Shea) Butter, Aloe Barbadensis Leaf Extract, Tocopherol, Fragrance', 23);

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `type`
--

CREATE TABLE `type` (
  `ID` int(11) NOT NULL,
  `name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `type`
--

INSERT INTO `type` (`ID`, `name`) VALUES
(1, 'nawilżenie'),
(2, 'oczyszczanie'),
(3, 'egg soap'),
(4, 'pianka'),
(5, 'maseczki'),
(6, 'pure essence'),
(7, 'after'),
(8, 'honey'),
(9, 'inne'),
(10, 'among us');

--
-- Indeksy dla zrzutów tabel
--

--
-- Indeksy dla tabeli `cosmetics`
--
ALTER TABLE `cosmetics`
  ADD PRIMARY KEY (`ID`);

--
-- Indeksy dla tabeli `type`
--
ALTER TABLE `type`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cosmetics`
--
ALTER TABLE `cosmetics`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=51;

--
-- AUTO_INCREMENT for table `type`
--
ALTER TABLE `type`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
